server:
    port: 80

thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
        content-type: text/html

spring:
    resources:
        static-locations: classpath:/templates/,classpath:/static/
